cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='CartAdd'),

]

online_shop/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'cart/', include('cart.urls')),
    url(r'order/', include('order.urls')),
    url(r'', include('shop.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.conf.urls import url
from . import views

app_name = 'order'
urlpatterns = [
    url(r'^$', views.order_detail, name='order'),

]

shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name="ProductByCategory"),
    url(r'^(?P<slug>[-\w]+)/(?P<id>\d+)/$', views.product_detail, name='ProductDetail'),
    url(r'^$', views.product_list, name="product_list")
]

cart/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models
from shop.models import Product
# Create your models here.


# Информация пользователя для оформления заказа и доставки товара
class Order(models.Model):
    first_name = models.CharField(max_length=64, verbose_name='Имя')
    second_name = models.CharField(max_length=64, verbose_name='Фамилия')
    email = models.EmailField(unique=True, verbose_name='Почта')
    phone = models.IntegerField( verbose_name='Телефон')
    city = models.CharField(max_length=30, verbose_name='Город')
    address = models.CharField(max_length=100, verbose_name='Адрес')
    delivery_date = models.DateTimeField(verbose_name='Дата доставки')

    def __str__(self):
        return '{} {}'.format(self.first_name, self.second_name)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


# Полная информация об оформлении заказа
class OrderItem(models.Model):
    product = models.ForeignKey(Product, verbose_name='Товар', on_delete=models.CASCADE)
    order = models.ForeignKey(Order, verbose_name='Личные данные', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='Количество', default=0)
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='Стоимость',default=0)


    def __str__(self):
        return 'Заказ: {}'.format(self.id)

shop/models.py
from django.db import models


# Модель категории
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductByCategory', args=[self.slug])


# Модель продукта
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name='Категория', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, verbose_name='Изображение товара', default='static/img/no-image.jpg')
    stock = models.PositiveIntegerField(verbose_name='На складе')
    available = models.BooleanField(default=True, verbose_name='Доступен')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductDetail', args=[self.slug, self.id])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

order/forms.py
from order.models import OrderItem, Order
from django import forms


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "__all__"

cart/views.py
from django.shortcuts import render, redirect
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


def cart_add(request, product_id):
    product = Product.objects.get(id=product_id)
    cart = Cart(request)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cart.add(product,
                 form.cleaned_data['quantity'],
                 form.cleaned_data['update'])
    return redirect(product.get_absolute_url())


def cart_remove(request, product_id):
    product = Product.objects.get(id=product_id)
    cart = Cart(request)
    cart.remove(product)
    return redirect('cart:CartDetail')


def cart_detail(request):
    cart = Cart(request)
    print(cart.cart.values())
    # for item in cart:
    #     item['update_quantity_form'] = CartAddProductForm(initial={
    #         'quantity': item['quantity'],
    #         'update': True
    #     })
    return render(request, 'cart/detail.html', {'cart': cart})

order/views.py
from django.shortcuts import render
from order.forms import OrderForm
from cart.cart import Cart
from order.models import OrderItem


def order_detail(request):
    cart = Cart(request)
    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid:
            order = form.save()
            for item in cart:
                print(item['product'])
                print(item['price'])
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         quantity=item['quantity'],
                                         price=item['price'])
            cart.clear()
            new_order = order
            print('ZAKAZ',order.id)
            return render(request, 'order/thanks_order.html', {'order':new_order})
    else:
        form = OrderForm()
        return render(request, 'order/order_detail.html', {'form':form,
                                                           'cart':cart})

shop/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.template.context_processors import csrf
from shop.models import Category, Product
from cart.forms import CartAddProductForm

from cart.cart import Cart


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = Category.objects.get(slug=category_slug)
        products = Product.objects.filter(category=category)
    return render(request, 'shop/product_list.html', {'categories': categories,
                                                      'products': products,
                                                      'category': category,
                                                      'cart':Cart(request)})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,  id=id, slug=slug,  available=True)
    cart_product_form = CartAddProductForm()
    context = {'product': product, 'cart_product_form': cart_product_form, 'cart':Cart(request)}
    context.update(csrf(request))
    return render_to_response('shop/product_detail.html', context)

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% block title %}
  Ваша корзина товаров
{% endblock %}
{% block content %}
  <h1>Ваша корзина товаров</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Цена</th>
        <th>Полная цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}

          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" width="100px" alt="" >
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td><form action="{% url 'cart:CartAdd' product.id %}" method="post" class="add">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                {% csrf_token %}
                <input type="submit" value="Обновить">
                </form>
            </td>
            <td><a href="{% url 'cart:CartRemove' product.id %}">Удалить</a></td>
            <td class="num">{{ item.price }} руб.</td>
            <td class="num">{{ item.total_price }} руб.</td>
          </tr>
      {% endwith %}
      {% endfor %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'order:order'%}">Оформить заказ</a>
  </p>
{% endblock %}

order/templates/order/order_detail.html
{% extends "shop/base.html" %}
{% block title %}
    Оформление заказа
{% endblock %}
{% block content %}


    <h1>Оформление заказа</h1>

    <div class="col-sm-4">
        <h2>Заполните форму</h2>
        <form class="order-form" action="#" method="post">
          {% csrf_token %}
          {{ form.as_p }}

          <input type="submit" value="Оформить заказ">
        </form>
    </div>
    <div class="col-sm-8">
        <h2>Ваш заказ</h2>
        <ul>
        {% for item in cart %}
            <li>Товар:{{ item.product }} | Количество:{{item.quantity}} | Цена: {{ item.price }}</li>
        {% endfor %}
        </ul>

    </div>


{% endblock %}

order/templates/order/thanks_order.html
{% extends "shop/base.html" %}
{% block title %}
    Оформление заказа
{% endblock %}
{% block content %}


    <h1>Оформление заказа</h1>

    <div class="container">
        <h2>Благодарим за заказ.</h2>
        <h2>Ваш заказ номер: {{order.id}}</h2>

        <h2>Менеджер скоро свяжется с вами.</h2>

        <a href="{% url 'shop:product_list'%}">Вернуться на главную страницу</a>
    </div>


{% endblock %}

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
    {% load staticfiles %}
    <title>{% block title %}{% endblock %}</title>
    <!-- Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <section id="header">
    <div class="top container">
        <a href="{% url 'shop:product_list'%}">Online shop</a>
    </div>
    <div class="top-bl">
      <div class="container">
        <div class="cart">
          <div class="cart">
                  {% with total_items=cart|length %}
                      {% if cart|length > 0 %}
                          Ваша корзина:
                  <a href="{% url 'cart:CartDetail' %}">
                      {{ cart.cart.keys|length}} тов. {{ cart.get_total_price }} руб.
                  </a>


                 {% else %}

                      Корзина пустая
                {% endif %}
              {% endwith %}


          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="content row" class="container">
    {% block content %}{% endblock %}

  </section>

</body>
</html>

shop/templates/shop/product_detail.html
{% extends "shop/base.html" %}
{% load staticfiles %}
{% block title %}
  {{ product.name }}
{% endblock %}
{% block content %}
  <div class="product-detail">
    <div class="col-sm-4">
      <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no-image.jpg'%}{% endif %}" class="img-responsive">
    </div>
    <div class="col-sm-8">
      <h1>{{ product.name }}</h1>
      <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
      <p class="price">
        {{ product.price }} руб.
      </p>
      <span>
        {{ product.description | linebreaks}}
      </span>
      <form action="{% url 'cart:CartAdd' product.id %}" method="post">
          {{ cart_product_form }}
          {% csrf_token %}
          <input type="submit" value="Добавить в корзину">
      </form>
    </div>
  </div>
{% endblock %}

shop/templates/shop/product_list.html
{% extends 'shop/base.html' %}
{% load staticfiles %}
{% block title %} {% if category %} {{ category.name }} {% else %} Страница товаров {% endif %} {% endblock %}

{% block content %}
<div id="sidebar" class="col-sm-3">
    <h3>Категории</h3>
    <ul>
        {% if not category %}<li class="selected" >{% else %}<li>{% endif %}
          <a href="{% url 'shop:product_list' %}">ВСЕ</a>
        </li>
        {% for cat in categories %}
        {% if category.slug == cat.slug %}<li class="selected">{% else %} <li> {% endif %}
            <a href="{{cat.get_absolute_url}}">{{ cat.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
 <div id="main" class="product_list col-sm-9">
    <h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
    <div class="items row">
      {% for product in products %}
        <div class="item col-sm-4">
          <a href="{{ product.get_absolute_url }}">
            {% if product.image %}<img src="{{ product.image.url }}" class="img-responsive" alt="{% static 'img/no-image.png' %}">{% else %}<img src="{% static 'img/no-image.png' %}" class="img-responsive">{% endif %}
          </a>
          <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
          {{ product.price }} руб.
        </div>

     {% endfor %}



    </div>
  </div>

{% endblock %}